### PR TITLE
Add the HDF5 High Level library to the package

### PR DESCRIPTION
**Pull request by hpages**
Hi Mike,

The HDF5 High Level (HL) library contains some interesting functionalities like the _HDF5 Dimension Scale API_ (H5DS module) and the _HDF5 Optimized Functions_ (H5DO module) that it would be nice to have in Rhdf5lib. See https://support.hdfgroup.org/HDF5/doc/HL/ for the list of stuff in the HL library. For the HDF5Array use case I'm particularly interested in the _HDF5 Dimension Scale API_  for storing the dimnames of an HDF5Array object in the file. At some point I might also play around with `H5DOread_chunk()` and `H5DOwrite_chunk()` to see if they can help improve performance in the context of block processing.

This PR only makes the HL available for non-Windows users. To make this work for Windows users, `libhdf5_hl.a` and `libhdf5_hl_cpp.a` would need to be built for 32-bit and 64-bit Windows and added to `Rhdf5lib/src/winlib/`. I don't know how much work this would involve but I could take a look.

Let me know if you see any problem with the PR. Thanks!

H.

### CODE REVIEW

**Comment by grimbough** [comment]
Hi Hervé, thanks for the pull request.  I'm currently dealing with some compiler settings that broke the Solaris build at CRAN.  I'll wait for those to trickle through the BioC build process, then I'll take a look at this.

I was looking at the high-level functions myself the other day.  `H5DOread_chunk()` seems interesting, doesn't it skip all the filters, so you get a gzipped (or whatever other filter you've applied) block of data?

**Comment by hpages** [comment]
Actually it turns out that `H5DOread_chunk()` has been moved to the core library and is now named `H5Dread_chunk()`. For some strange reason it's not documented at https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html but it's definitely part of the H5D interface. See `hdf5-1.10.3/src/H5Dpublic.h` for its prototype.

Yes it's very low-level. It loads the raw chunk data in a buffer and that's it. So yes it's fast but you potentially have to apply many transformations to the raw data (uncompress, shuffle, etc...) before you can do anything with it. I use it in `HDF5Array::h5mread()` (method 5, see `read_data_4_5()` in `HDF5Array/src/h5mread.c`) but ran into some difficulty with shuffled character data so added a warning that method 5 is not ready for general use. Anyway method 6 outperforms all methods in almost all situations so is the default. There are a few situations where method 5 beats method 6 but not by much and these situations are not that common.

Note that being able to use `H5DOread_chunk()` and the _HDF5 Dimension Scale API_ were my 2 motivations for adding the HL library to Rhdf5lib but now that I found `H5Dread_chunk()` I only need the HL library for the  _HDF5 Dimension Scale API_. It turns out that I'm not planning to start any work on this before January though so this PR can wait. Thanks!

**Comment by grimbough** [comment]
Hi Herve,

Sorry, this fell off my radar for a while.  There's now a 10-4_withHL branch that contains HDF5 1.10.4 with both the C++ and HL interfaces, and it should work for Windows as well as Linux/Mac.  

I don't want to incorporate it into the master/BioC branch until I've had a chance to test on Solaris - every time I've made a significant change there's a lag and then I find out the CRAN build is failing so I'm trying to head that off before it happens.

Feel free to experiment with this and let me know if something's missing, and I'll update once I'm happy it's stable across all platforms.

**Comment by hpages** [comment]
Hi Mike,

Excellent! I'll give a try to the 10-4_withHL branch ASAP. Thanks!

Also sorry for the late answer, I was on vacation.

H.

**Comment by hpages** [comment]
Hi Mike,

Thanks for adding the HL interface and for supporting it on Windows!

I took a look at your `10-4_withHL` branch today and did some quick testing (just tried to call `H5DSis_scale()` from HDF5Array/src/DSet.c after adding `#include "hdf5_hl.h"` to it and replacing `Rhdf5lib::pkgconfig("PKG_C_LIBS")` with `Rhdf5lib::pkgconfig("PKG_C_HL_LIBS")` in HDF5Array/src/Makevars). Everything seems to work as expected. I only tested on my laptop though (Ubuntu 16.04.5 LTS). Testing on other platforms would require much more time but I'm always for pushing changes to git.bioconductor.org and let the build system do that kind of testing for us. This is why we have the build system after all!

Also I only tried to link C code, no C++ code.

BTW thanks for updating the HDF5 code from 1.10.3 to 1.10.4 and for adding the vignettes/downloadHDF5.R script! (Note that this new script makes the "Creating hdf5small_cxx.tar.gz" section in vignettes/README.md obsolete.)

Cheers,
H.

**Comment by grimbough** [comment]
Thanks for the fedback on this Hervé.  Now the release is done I've updated to HDF5 1.10.5 added this to the devel branch on BioC.  We'll see what the build machines make of it.  If you're not using any of the HL functionality yet this shouldn't chnge anything, but as you noted, if you switch to `Rhdf5lib::pkgconfig("PKG_C_HL_LIBS")` it should be available to link against.

**Comment by hpages** [comment]
Hi Mike,

Thanks for the update. AFAICT everything looks fine on the BioC 3.10 report so I'm closing this. I'll start using the _HDF5 Dimension Scale API_  very soon in the HDF5Array package to support storage and retrieval of the dimnames of an HDF5Array object to and from the HDF5 file. I'll open issues if I run into problems.

Thanks again for adding this functionality.

H.

**Comment by hpages** [comment]
Hey Mike, I was finally able to implement [this](https://github.com/Bioconductor/HDF5Array/commit/c2cd0268c2d1946ec92715ece0e90a841b80a89b) on top of the HDF5 HL library. Thanks again for adding the HL library to Rhdf5lib!
H.

**Pull request closed without merging**
